// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO3hYaLVDB_6OsVE7FL5d_Beh9lGdc5IA',
    appId: '1:1048150948710:web:ea03b6e5973c4f5a7f26a7',
    messagingSenderId: '1048150948710',
    projectId: 'campus-vibes-484fe',
    authDomain: 'campus-vibes-484fe.firebaseapp.com',
    storageBucket: 'campus-vibes-484fe.firebasestorage.app',
    measurementId: 'G-2JWBYPT6HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvzAW2YpjyIsuk0f7r50QNVhWB9JZ_tN4',
    appId: '1:1048150948710:android:42bd0c241416c8067f26a7',
    messagingSenderId: '1048150948710',
    projectId: 'campus-vibes-484fe',
    storageBucket: 'campus-vibes-484fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTi3FwNolOBvHqXX3_g2ewO3yk6A9P3CA',
    appId: '1:1048150948710:ios:fd01e0d5dc1ea8c67f26a7',
    messagingSenderId: '1048150948710',
    projectId: 'campus-vibes-484fe',
    storageBucket: 'campus-vibes-484fe.firebasestorage.app',
    iosBundleId: 'com.example.campusVibes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTi3FwNolOBvHqXX3_g2ewO3yk6A9P3CA',
    appId: '1:1048150948710:ios:fd01e0d5dc1ea8c67f26a7',
    messagingSenderId: '1048150948710',
    projectId: 'campus-vibes-484fe',
    storageBucket: 'campus-vibes-484fe.firebasestorage.app',
    iosBundleId: 'com.example.campusVibes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO3hYaLVDB_6OsVE7FL5d_Beh9lGdc5IA',
    appId: '1:1048150948710:web:924eb84dd8026ec37f26a7',
    messagingSenderId: '1048150948710',
    projectId: 'campus-vibes-484fe',
    authDomain: 'campus-vibes-484fe.firebaseapp.com',
    storageBucket: 'campus-vibes-484fe.firebasestorage.app',
    measurementId: 'G-6LENHJT3ZS',
  );
}
