// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAATMeHkZg9cwQsCpgxjiV-Ums0gc7uAbU',
    appId: '1:883372026398:web:e77b36dcd1d9ea22b11c0f',
    messagingSenderId: '883372026398',
    projectId: 'techm-training-1c1e3',
    authDomain: 'techm-training-1c1e3.firebaseapp.com',
    storageBucket: 'techm-training-1c1e3.firebasestorage.app',
    measurementId: 'G-2FWXM35Z10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_OpIcr8i4DCuqACs140V-RNGEAjZaZeo',
    appId: '1:883372026398:android:e75fffd63936723db11c0f',
    messagingSenderId: '883372026398',
    projectId: 'techm-training-1c1e3',
    storageBucket: 'techm-training-1c1e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5FkZAzR_5bIzkOklfjHgtjAa4A9n295s',
    appId: '1:883372026398:ios:4fdae38418fbc444b11c0f',
    messagingSenderId: '883372026398',
    projectId: 'techm-training-1c1e3',
    storageBucket: 'techm-training-1c1e3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5FkZAzR_5bIzkOklfjHgtjAa4A9n295s',
    appId: '1:883372026398:ios:4fdae38418fbc444b11c0f',
    messagingSenderId: '883372026398',
    projectId: 'techm-training-1c1e3',
    storageBucket: 'techm-training-1c1e3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAATMeHkZg9cwQsCpgxjiV-Ums0gc7uAbU',
    appId: '1:883372026398:web:1bd06bdfffe5e14ab11c0f',
    messagingSenderId: '883372026398',
    projectId: 'techm-training-1c1e3',
    authDomain: 'techm-training-1c1e3.firebaseapp.com',
    storageBucket: 'techm-training-1c1e3.firebasestorage.app',
    measurementId: 'G-Y468DPT15B',
  );
}
